blank_issues_enabled: true
contact_links:
  - name: A list of GTA IV issues that weren't addressed in official patches
    url: https://github.com/GTAmodding/GTAIV-Issues-List/issues
    about: 'Submit original game issues here'
